name: Acceptance Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

    acceptance:
        name: Build and Test the Vite Application

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]

        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Node.js 16
              uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: yarn

            - name: Install dependencies
              run: yarn --frozen-lockfile --prefer-offline

            - name: Build application
              run: yarn build

            - name: Run E2E Tests on Linux
              if: runner.os == 'Linux'
              run: |
                  npx playwright install --with-deps chrome firefox
                  yarn test:e2e --project Chromium Firefox 'Pixel 5'

            - name: Run E2E Tests on macOS
              if: runner.os == 'macOS'
              run: |
                  npx playwright install --with-deps webkit
                  yarn test:e2e --project Safari 'iPhone 13'

            - name: Run E2E Tests on Windows
              if: runner.os == 'Windows'
              run: |
                  npx playwright install --with-deps msedge
                  yarn test:e2e --project Edge

            - name: Upload traces from failed tests
              uses: actions/upload-artifact@v2
              if: failure()
              with:
                  name: test-results
                  path: test-results/
                  retention-days: 7

            - name: Upload Playwright test report
              uses: actions/upload-artifact@v2
              if: always()
              with:
                name: playwright-report-${{ matrix.os }}
                path: playwright-report/
                if-no-files-found: ignore
                retention-days: 7
